version: '2'

services:
  db:
    image: postgres
  web:
    build: .
    command: pip install -r requirements.txt
    command: python src/manage.py runserver 0.0.0.0:5000
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    depends_on:
      - db
